### ISSUE TITLE
[Feature] Create Helm Chart

### ISSUE THREAD

**Issue by patsevanton** [linkedin/cruise-control-ui#127] opened 2024-09-25 13:00 UTC
Please consider creating a helm chart.
This will make it easier to install and deploy the application in kubernetes
Thanks!

**Comment by frivoire** [comment] 2024-09-26 07:24
This issue seems to be a duplicate of https://github.com/linkedin/cruise-control-ui/issues/113

**Closed as completed** 2024-09-26 08:06 UTC
